[package]
name = "outer-workspace-crate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
example-lib = { path = "../inner-workspace/example-lib" }
